import { StyleSheet } from 'react-native';
export const colors = {
  bg: '#0c1519',
  panel: '#16252b',
  raised: '#20343b',
  border: '#30464d',
  text: '#edf4ed',
  muted: '#99adb0',
  gold: '#e8bf70',
  green: '#78bc87',
  blue: '#66bdd8',
  red: '#ef8580',
  purple: '#bba0ec',
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 16, gap: 12 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  title: { color: colors.text, fontSize: 26, fontWeight: '800' },
  heading: { color: colors.text, fontSize: 17, fontWeight: '700' },
  text: { color: colors.text, fontSize: 14, lineHeight: 20 },
  muted: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  gold: { color: colors.gold, fontWeight: '700' },
  card: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 8,
  },
  button: {
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.raised,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primary: { backgroundColor: colors.gold },
  buttonText: { color: colors.text, fontWeight: '700', fontSize: 14 },
  disabled: { opacity: 0.38 },
  input: {
    minHeight: 48,
    color: colors.text,
    backgroundColor: colors.panel,
    borderRadius: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  overlay: { flex: 1, backgroundColor: '#000b', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: colors.panel,
    padding: 20,
    gap: 14,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
  },
});
