import type { DifficultyConfig } from '../domain/types.js';
import { STATS } from '../domain/rules/stats.js';
import { ABILITY_ORDER } from './abilities.js';

export const normalConfig: DifficultyConfig = {
  armorEffectiveness: 1.5,
  baseHp: STATS.maxHp.base,
  baseEnergy: STATS.maxEnergy.base,
  hpRegen: STATS.hpRegen.base,
  energyRegen: STATS.energyRegen.base,
  coinsPerSec: STATS.coinsPerSec.base,
  startingCoins: 250,

  shootCost: STATS.shootCost.base,
  shootCooldown: STATS.shootCooldown.base,
  arrowTravelTime: 1 / STATS.arrowSpeed.base,

  abilities: Object.fromEntries(
    ABILITY_ORDER.map((id) => [
      id,
      {
        cost: STATS[`${id}.cost`].base,
        cooldown: STATS[`${id}.cooldown`].base,
      },
    ]),
  ) as DifficultyConfig['abilities'],

  levelTimerBase: 15,
  levelTimerStep: 2,

  spawnTickInterval: STATS.spawnInterval.base,
  spawnP0: 0.00054,
  spawnDP: 0.000045,

  spiderSpeedBase: 0.08,
  spiderSpeedStep: 0.004,
  spiderDamageBase: 20,
  spiderDamageGrowth: 0.08,
  spiderVariance: 0.3,

  spiderChanceFat: 0.05,
  spiderChanceFast: 0.07,
  spiderChanceNinja: 0.02,
  spiderChanceBurner: 0.01,
  spiderChanceTank: 0.02,

  talents: {
    endurance: { maxRanks: 7, unlocksAtLevel: 0 },
    spiderArmor: { maxRanks: 10, unlocksAtLevel: 20 },
    tireless: { maxRanks: 5, unlocksAtLevel: 10 },
    agility: { maxRanks: 5, unlocksAtLevel: 0 },
    healBoost: { maxRanks: 5, unlocksAtLevel: 40 },
    hunterMastery: { maxRanks: 5, unlocksAtLevel: 0 },
    piercingReward: { maxRanks: 8, unlocksAtLevel: 10 },
    criticalShot: { maxRanks: 10, unlocksAtLevel: 10 },
    eagleEye: { maxRanks: 1, unlocksAtLevel: 20 },
    improvedCriticalShot: { maxRanks: 8, unlocksAtLevel: 30 },
    agileCriticalShot: { maxRanks: 5, unlocksAtLevel: 30 },
    vampirism: { maxRanks: 5, unlocksAtLevel: 0 },
    improvedPrep: { maxRanks: 5, unlocksAtLevel: 20 },
    recharge: { maxRanks: 1, unlocksAtLevel: 60 },
    permafrost: { maxRanks: 5, unlocksAtLevel: 20 },
    volley: { maxRanks: 1, unlocksAtLevel: 10 },
    volleyMastery: { maxRanks: 5, unlocksAtLevel: 20 },
    rapidFire: { maxRanks: 7, unlocksAtLevel: 40 },
    killingStreak: { maxRanks: 10, unlocksAtLevel: 20 },
    enthusiasm: { maxRanks: 5, unlocksAtLevel: 30 },
    improvedKillingStreak: { maxRanks: 5, unlocksAtLevel: 40 },
    dutyBound: { maxRanks: 5, unlocksAtLevel: 40 },
    blizzardMastery: { maxRanks: 6, unlocksAtLevel: 10 },
    hunterReward: { maxRanks: 5, unlocksAtLevel: 20 },
    greed: { maxRanks: 5, unlocksAtLevel: 0 },
    quickInstinct: { maxRanks: 10, unlocksAtLevel: 40 },
    hunterArsenal: { maxRanks: 5, unlocksAtLevel: 0 },
    improvedEndurance: { maxRanks: 7, unlocksAtLevel: 0 },
    improvedAgility: { maxRanks: 7, unlocksAtLevel: 0 },
    improvedIntellect: { maxRanks: 7, unlocksAtLevel: 0 },
    magicArmor: { maxRanks: 7, unlocksAtLevel: 10 },
    warriorArmor: { maxRanks: 5, unlocksAtLevel: 10 },
    titanArmor: { maxRanks: 5, unlocksAtLevel: 50 },
    divineShield: { maxRanks: 1, unlocksAtLevel: 30 },
    shieldBlock: { maxRanks: 8, unlocksAtLevel: 10 },
    lastHope: { maxRanks: 1, unlocksAtLevel: 20 },
    improvedLastHope: { maxRanks: 5, unlocksAtLevel: 30 },
    bestDefense: { maxRanks: 10, unlocksAtLevel: 40 },
    willToWin: { maxRanks: 5, unlocksAtLevel: 50 },
    adrenaline: { maxRanks: 1, unlocksAtLevel: 60 },
    marauder: { maxRanks: 3, unlocksAtLevel: 30 },
  },
};
